const CART = {
  SET_CHECKOUT_STATUS: 'SET_CHECKOUT_STATUS',
  SET_CART_ITEMS: 'SET_CART_ITEMS',
  PUSH_PRODUCT_TO_CART: 'PUSH_PRODUCT_TO_CART',
  INCREMENT_ITEM_QUANTITY: 'INCREMENT_ITEM_QUANTITY',
  
}

const PRODUCTS = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  DESCREMENT_PRODUCT_INVENTORY: 'DESCREMENT_PRODUCT_INVENTORY'
}

export { 
  CART,
  PRODUCTS
}